"""Adds new columns

Revision ID: 75502da92c83
Revises: f99a8ce737d6
Create Date: 2023-10-25 18:24:29.106009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75502da92c83'
down_revision = 'f99a8ce737d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure', sa.String(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('servings')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('unit_of_measure')
        batch_op.drop_column('quantity')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
