"""alter database to be adaptable to multiple recipes

Revision ID: 8c671221aeea
Revises: 75502da92c83
Create Date: 2023-10-26 16:12:00.382545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c671221aeea'
down_revision = '75502da92c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('unit_of_measure')

    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes_ingredients', schema=None) as batch_op:
        batch_op.drop_column('processed')
        batch_op.drop_column('unit_of_measure')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
